-- Модул "Файлове": заявка с уникален линк + качените по нея файлове.
-- Изпълнете този скрипт в Supabase -> SQL Editor.

create table if not exists file_requests (
    id bigint generated by default as identity primary key,
    request_id text not null unique,
    title text not null,
    note text,
    created_at timestamptz not null default now()
);

create table if not exists file_request_uploads (
    id bigint generated by default as identity primary key,
    request_id text not null references file_requests(request_id) on delete cascade,
    uploader_name text,
    filename text not null,
    storage_path text not null,
    file_url text,
    size_bytes bigint,
    created_at timestamptz not null default now()
);

create index if not exists file_request_uploads_request_id_idx
    on file_request_uploads (request_id);

-- Достъпът минава през сървъра (service role), затова RLS се изключва,
-- както при останалите таблици в проекта.
alter table file_requests disable row level security;
alter table file_request_uploads disable row level security;
